---
include:
  - board: ergohaven
    shield: k03_qube qube dongle_screen
    keymap: k03_ruen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: k03_qube_ruen-ergohaven-zmk
